export const parentConstants = {
    
    GETALL_REQUEST: 'PARENT_GETALL_REQUEST',
    GETALL_SUCCESS: 'PARENT_GETALL_SUCCESS',
    GETALL_FAILURE: 'PARENT_GETALL_FAILURE',

    GETCHILD_REQUEST: 'PARENT_GETCHILD_REQUEST',
    GETCHILD_SUCCESS: 'PARENT_GETCHILD_SUCCESS',
    GETCHILD_FAILURE: 'PARENT_GETCHILD_FAILURE',

    GET_SESSIONS_REQUEST: 'PARENT_GET-S_REQUEST',
    GET_SESSIONS_SUCCESS: 'PARENT_GET-S_SUCCESS',
    GET_SESSIONS_FAILURE: 'PARENT_GET-S_FAILURE',
};

