export const parentConstants = {
    LOGIN_REQUEST: 'PARENT_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'PARENT_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'PARENT_LOGIN_FAILURE',
    
    LOGOUT: 'PARENT_LOGOUT',

    GETALL_REQUEST: 'PARENT_GETALL_REQUEST',
    GETALL_SUCCESS: 'PARENT_GETALL_SUCCESS',
    GETALL_FAILURE: 'PARENT_GETALL_FAILURE',


    GETAUTH_REQUEST: 'PARENT_GETAUTH_REQUEST',
    GETAUTH_SUCCESS: 'PARENT_GETAUTH_SUCCESS',
    GETAUTH_FAILURE: 'PARENT_GETAUTH_FAILURE',

    GETCHILD_REQUEST: 'PARENT_GETCHILD_REQUEST',
    GETCHILD_SUCCESS: 'PARENT_GETCHILD_SUCCESS',
    GETCHILD_FAILURE: 'PARENT_GETCHILD_FAILURE',

    GET_SESSIONS_REQUEST: 'PARENT_GET-S_REQUEST',
    GET_SESSIONS_SUCCESS: 'PARENT_GET-S_SUCCESS',
    GET_SESSIONS_FAILURE: 'PARENT_GET-S_FAILURE',
};

